baseURL = 'https://docs.grugrut.net/containers/'
languageCode = 'ja-jp'
title = 'Container Docs'
#theme = 'geekdoc'

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
[taxonomies]
  tag = "tags"

[minify]
  disableHTML = true

[module]
[[module.imports]]
path = "github.com/bep/docuapi/v2"
[params]
search = true
